CREATE VIEW IF NOT EXISTS AIR_CIA_ROTES AS 

SELECT
  AC.ATIVIDADES_AEREAS,
  A.NAME,
  V.ICAO_AERODROMO_ORIGEM,
  A.STATE,
  V.ICAO_AERODROMO_DESTINO
FROM AIR_CIA AC
JOIN VRA_DATA V
 ON AC.IATA = V.ICAO_EMPRESA_AEREA
JOIN AERODROMOS A
 ON V.ICAO_AERODROMO_ORIGEM = A.ICAO
 AND V.ICAO_AERODROMO_DESTINO = A.ICAO


CREATE VIEW IF NOT EXISTS AIRPORTS AS 

SELECT
  A.NAME,
  A.ICAO,
  A.STATE,
  AC.ATIVIDADES_AEREAS,
  COUNT(V.ICAO_AERODROMO_ORIGEM) AS QTD_ROTAS_ORIGEM,
  COUNT(V.ICAO_AERODROMO_DESTINO) AS QTD_ROTAS_DESTINO,
  SUM(QTD_ROTAS_ORIGEM, QTD_ROTAS_DESTINO) AS QTD_TOTAL
FROM AIR_CIA AC
JOIN AERODROMOS A
 ON A.ICAO = AC.ICAO
JOIN VRA_DATA V
 ON A.ICAO = V.ICAO_AERODROMO_ORIGEM
 AND A.ICAO = V.ICAO_AERODROMO_DESTINO
GROUP BY A.NAME,
         A.ICAO




